AWSTemplateFormatVersion: '2010-09-09'
Description: Push Notification Service.
Parameters:
  GitHubToken:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    NoEcho: true
  GitHubOwner:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    NoEcho: true
  AuthenticationTopicArn:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 500
    MinLength: 5
  ApiLogicalId:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 500
    MinLength: 5
  ApiRootResource:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
  AuthorizerLogicalId:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
  UserResource:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
  CognitoPoolID:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
  BackendAPI:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
  CognitoClientID:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
Resources: 

  ChatbotTaskLambda: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./chatbotTaskLambda.yaml
      Parameters:
        FunctionName: LambdaHookBot-botService
        FunctionDescription: Lambda function that update a job and store it to dynamodb.
        FunctionHandler: index.handler
        FunctionMemorySize: "128"
        FunctionRuntimeVersion: nodejs12.x
        FunctionTimeout: "10"

        ServiceTag: bot-service
        ApplicationTag: bot
        ApiTypeTag: bot
        PathRole: /

        BackendAPI: !Ref BackendAPI

  LambdaHookFullfillTaskLambda: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./LambdaHookFulfillTask.yaml
      Parameters:
        FunctionName: HookFulfillTaskLambda-botService
        FunctionDescription: Lambda function that update a job and store it to dynamodb.
        FunctionHandler: index.handler
        FunctionMemorySize: "128"
        FunctionRuntimeVersion: nodejs12.x
        FunctionTimeout: "10"

        ServiceTag: bot-service
        ApplicationTag: bot
        ApiTypeTag: bot
        PathRole: /

        BackendAPI: !Ref BackendAPI

