AWSTemplateFormatVersion: '2010-09-09'
Description: Push Notification Service.
Parameters:
  KMSKeyArn:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 350
    MinLength: 5
  KMSKeyID:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 350
    MinLength: 5
  ArtifactStoreBucketName:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 50
    MinLength: 5
  BackendAPI:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    MaxLength: 50
    MinLength: 5
  GitHubOwner:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    NoEcho: true
  GitHubToken:
    Type: String
    Description: Name the bucket used for storing the Pipeline Artifacts.
    NoEcho: true
Resources: 

  UpdateJobMethod: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./chatbotTaskLambda.yaml
      Parameters:
        FunctionName: TaskBot-botService
        FunctionDescription: Lambda function that update a job and store it to dynamodb.
        FunctionHandler: index.handler
        FunctionMemorySize: "128"
        FunctionRuntimeVersion: nodejs12.x
        FunctionTimeout: "10"

        ServiceTag: bot-service
        ApplicationTag: bot
        ApiTypeTag: bot
        PathRole: /

        BackendAPI: !Ref BackendAPI

